[workspace]
channels = ["conda-forge"]
name = "RandomViewer"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pyside6 = ">=6.9.1,<7"
send2trash = ">=1.8.3,<2"
pyinstaller = ">=6.15.0,<7"
